apiVersion: apps/v1
kind: Deployment

metadata:
  name: frontend
  namespace: devops-case

spec:
  replicas: 1

  selector:
    matchLabels:
      app: frontend

  template:
    metadata:
      labels:
        app: frontend

    spec:
      containers:
        - name: frontend
          image: devops-case-frontend:k8s
          imagePullPolicy: Never

          ports:
            - containerPort: 80